### ISSUE TITLE
Add `logger` option to channels

### ISSUE THREAD

**Issue by jefflunt** [jefflunt/mini-pubsub#45]
Add the ability to specify a `logger` inside the `channels.yml` file.

The current format is:

```yaml
channel_name:
  subscribers:
    ... subscribers list ...
```

```yaml
channel_name:
  logger: [any valid sender spec]
  subscribers:
    ... subscribers list ...
```

So, a channel called `default` that logs to `stdout` would look like:

```yaml
default:
  logger: stdout
  subscribers:
    ... subscribers list...
```
