### ISSUE TITLE
Create `subscribers` key in the `channels.yml` file

### ISSUE THREAD

**Issue by jefflunt** [jefflunt/mini-pubsub#47]
Subscribers need to be under their own `subscribers` key. This will require a change in the `ChannelSerializer` class.

I.e. the current format is:

```yaml
channel_name:
  subscriber_id: [sender spec]
  ... more subscribers ...
```

... but the new format should be:

```yaml
channel_name:
  subscribers:
    subscriber_id: [sender spec]
    ... more subscribers ...
```
